# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Build and test Python package

on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9] #3.7, 3.8,
        os: [ubuntu-latest] #, windows-latest, macOS-latest
    steps:
    - name: Prepare Github Actions
      uses: actions/checkout@v2
    - name: Install TeXLive
      uses: xu-cheng/texlive-action/full@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        python -m pip install flake8 pytest
        python -m pip install pytest-mpl
        pip install -e .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --max-complexity=10 --max-line-length=127 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics  --select=E9,F63,F7,F82
    - name: Test with pytest
      run: |
        sudo locale-gen en_US.UTF-8
        sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
        pytest --mpl-baseline-relative